apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydemo
  template:
    metadata:
      labels:
        app: mydemo
    spec:
      containers:
      - name: mydemo
        image: docker.io/library/mydemo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: mydemo-service
spec:
  selector:
    app: mydemo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3333
  type: ClusterIP